name: Daily Update For Srs Files

on:
  schedule:
    - cron: '0 18 */3 * *' # Every 3 days at 2 AM UTC+8 is 18:00 UTC
  workflow_dispatch: # Allows manual trigger
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Change directory to tools and run scripts
      run: |
        cd tools
        python list_json.py
        bash convert2srs.sh

    
